# Generated by rust2rpm 27
%bcond check 1

%global crate git-cinnabar

# MANUAL EDIT
%global gitexecdir %{_libexecdir}/git-core

Name:           rust-git-cinnabar
Version:        0.7.3
Release:        %autorelease
Summary:        Git remote helper to interact with mercurial repositories

License:        MPL-2.0 AND GPL-2.0
URL:            https://crates.io/crates/git-cinnabar
Source:         %{crates_source}
# Automatically generated patch to strip dependencies and normalize metadata
Patch:          git-cinnabar-fix-metadata-auto.diff
# Manually created patch for downstream crate metadata changes
Patch:          git-cinnabar-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Git remote helper to interact with mercurial repositories.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# output of %%cargo_license_summary
# (MIT OR Apache-2.0) AND Unicode-DFS-2016
# 0BSD OR MIT OR Apache-2.0
# Apache-2.0 OR MIT
# Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT
# BSD-2-Clause
# BSD-2-Clause OR Apache-2.0 OR MIT
# MIT
# MIT OR Apache-2.0
# MIT OR Apache-2.0 OR Zlib
# MIT OR Zlib OR Apache-2.0
# MPL-2.0 AND GPL-2.0
# Unlicense OR MIT
# Zlib OR Apache-2.0 OR MIT
License:        (MIT OR Apache-2.0) AND Unicode-DFS-2016 AND (0BSD OR MIT OR Apache-2.0) AND (Apache-2.0 OR MIT) AND (Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT) AND BSD-2-Clause AND (BSD-2-Clause OR Apache-2.0 OR MIT) AND MIT AND (MIT OR Apache-2.0) AND (MIT OR Apache-2.0 OR Zlib) AND (MIT OR Zlib OR Apache-2.0) AND (MPL-2.0 AND GPL-2.0) AND (Unlicense OR MIT) AND (Zlib OR Apache-2.0 OR MIT)
# LICENSE.dependencies contains a full license breakdown
# MANUAL EDIT
Requires:       git-core
# MANUAL EDIT
Obsoletes:      git-cinnabar < 0.6

%description -n %{crate} %{_description}

%files       -n %{crate}
%license MPL-2.0
%license git-core/COPYING
%license git-core/LGPL-2.1
%license LICENSE.dependencies
%doc README.md
%{_bindir}/git-cinnabar
# MANUALL EDIT
%{gitexecdir}/git-remote-hg

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install
install -d %{buildroot}%{gitexecdir}
ln -sr %{buildroot}%{_bindir}/git-cinnabar %{buildroot}%{gitexecdir}/git-remote-hg

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
