# Generated by rust2rpm 24
%bcond_without check

%global crate git-cinnabar
%global gitexecdir %{_libexecdir}/git-core

Name:           git-cinnabar
Version:        0.6.1
Release:        %autorelease
Summary:        Git remote helper to interact with mercurial repositories

License:        MPL-2.0 AND GPL-2.0
URL:            https://crates.io/crates/git-cinnabar
Source:         %{crates_source}

Patch:          git-cinnabar-disable-self-update.diff
# Automatically generated patch to strip foreign dependencies
Patch:          git-cinnabar-fix-metadata-auto.diff
# Manually created patch for downstream crate metadata changes
Patch:          git-cinnabar-fix-metadata.diff

BuildRequires:  rust-packaging >= 21
	
Requires:       git-core

%global _description %{expand:
Git remote helper to interact with mercurial repositories.}

%description %{_description}


%files
%license git-core/COPYING
%license git-core/LGPL-2.1
%doc README.md
%{gitexecdir}/git-cinnabar
%{gitexecdir}/git-remote-hg

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
# todo 
# not use cargo install , but manully
# cause we will install it into {gitexecdir} and symlink to git-remote-hg
%cargo_install
install -d %{buildroot}%{gitexecdir}
mv %{buildroot}%{_bindir}/git-cinnabar  %{buildroot}%{gitexecdir}
#install -p -m 0755 %{buildroot}%{_bindir}/git-cinnabar %{buildroot}%{gitexecdir}
cd %{buildroot}%{gitexecdir}
ln -s git-cinnabar %{buildroot}%{gitexecdir}/git-remote-hg

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
