# Generated by rust2rpm 25
%bcond_without check

%global crate git-cinnabar
%global gitexecdir %{_libexecdir}/git-core

Name:           git-cinnabar
Version:        0.6.2
Release:        %autorelease
Summary:        Git remote helper to interact with mercurial repositories

License:        MPL-2.0 AND GPL-2.0
URL:            https://crates.io/crates/git-cinnabar
Source:         %{crates_source}
# Automatically generated patch to strip dependencies and normalize metadata
Patch:          git-cinnabar-fix-metadata-auto.diff
# Manually created patch for downstream crate metadata changes
Patch:          git-cinnabar-fix-metadata.diff

Requires:       git-core
BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Git remote helper to interact with mercurial repositories.}

%description %{_description}

%files
%license git-core/COPYING
%license git-core/LGPL-2.1
%license LICENSE.dependencies
%doc README.md
%{gitexecdir}/git-cinnabar
%{gitexecdir}/git-remote-hg

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install
install -d %{buildroot}%{gitexecdir}
mv %{buildroot}%{_bindir}/git-cinnabar  %{buildroot}%{gitexecdir}
cd %{buildroot}%{gitexecdir}
ln -s git-cinnabar %{buildroot}%{gitexecdir}/git-remote-hg

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
