# Generated by rust2rpm 24
%bcond_without check
%global debug_package %{nil}

%global crate all_asserts

Name:           rust-all_asserts
Version:        2.3.1
Release:        %autorelease
Summary:        For multiple types of asserts that don't exist in the standard library

License:        Apache-2.0
URL:            https://crates.io/crates/all_asserts
Source:         %{crates_source}

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
A crate for multiple types of asserts that don't exist in the standard
library.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/CODE_OF_CONDUCT.md
%doc %{crate_instdir}/CONTRIBUTING.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
